### ISSUE TITLE
fetch messages

### ISSUE THREAD

**Issue by thewilloftheshadow** [packcord/discord-giveaways#5]
UnhandledPromiseRejectionWarning: TypeError: channel.messages.fetch is not a function

    at giveaways.filter.forEach (/rbd/pnpm-volume/65ee1f32-e498-484c-a45c-24697963cebe/node_modules/.registry.npmjs.org/discord-giveaways/2.1.18/node_modules/discord-giveaways/utils.js:194:50)

    at Array.forEach (<anonymous>)

    at Timeout.check [as _onTimeout] (/rbd/pnpm-volume/65ee1f32-e498-484c-a45c-24697963cebe/node_modules/.registry.npmjs.org/discord-giveaways/2.1.18/node_modules/discord-giveaways/utils.js:186:39)

    at ontimeout (timers.js:438:13)

    at tryOnTimeout (timers.js:300:5)

    at listOnTimeout (timers.js:263:5)

    at Timer.processTimers (timers.js:223:10)

Seems to be a problem with the

**Comment by Niromash** [comment]
You use discord js 11, replace channel.messages.fetch to channel.fetchMessages

**Comment by Androz2091** [comment]
@thewilloftheshadow try to update the package and restarts your bot
